// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfshnsitewulziaqgsnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmc2huc2l0ZXd1bHppYXFnc25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTE3NDYsImV4cCI6MjA3MTUyNzc0Nn0.MXnl9Ev71RtKt8TSpK8RgUMtLBpQfvZG8vy5As4PTN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});